export const DEFAULT_CURRENCY = "CNY";
export const CONTACT_INFO_ERROR =
  "廣告與作品內容不得包含手機、微信、Email、LINE、Telegram、QQ 等站外聯絡資訊。";

export enum CooperationMode {
  COMMISSION_5 = "COMMISSION_5",
  PLATFORM_BUYOUT_SERVICE = "PLATFORM_BUYOUT_SERVICE",
  PLATFORM_OWNED_INVENTORY = "PLATFORM_OWNED_INVENTORY"
}

export enum OrderStatus {
  CREATED = "CREATED",
  DEPOSIT_PENDING = "DEPOSIT_PENDING",
  DEPOSIT_PAID = "DEPOSIT_PAID",
  AWAITING_KNITTER_ACCEPTANCE = "AWAITING_KNITTER_ACCEPTANCE",
  IN_PROGRESS = "IN_PROGRESS",
  SENT_TO_PLATFORM = "SENT_TO_PLATFORM",
  PLATFORM_INSPECTION = "PLATFORM_INSPECTION",
  BALANCE_PENDING = "BALANCE_PENDING",
  BALANCE_PAID = "BALANCE_PAID",
  PLATFORM_SHIPPED = "PLATFORM_SHIPPED",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  REFUNDING = "REFUNDING",
  REFUNDED = "REFUNDED",
  DISPUTED = "DISPUTED"
}

export enum PaymentType {
  DEPOSIT = "DEPOSIT",
  BALANCE = "BALANCE",
  AD_FEE = "AD_FEE"
}

export enum PaymentProvider {
  MOCK = "MOCK",
  WECHAT_JSAPI = "WECHAT_JSAPI",
  WECHAT_H5 = "WECHAT_H5",
  WECHAT_NATIVE = "WECHAT_NATIVE",
  WECHAT_APP = "WECHAT_APP",
  ALIPAY_WAP = "ALIPAY_WAP",
  ALIPAY_NATIVE = "ALIPAY_NATIVE",
  ALIPAY_APP = "ALIPAY_APP"
}

export enum OrderChannel {
  H5 = "H5",
  MINI_PROGRAM = "MINI_PROGRAM",
  APP = "APP",
  ADMIN = "ADMIN"
}

export enum ListingStatus {
  DRAFT = "DRAFT",
  PENDING_REVIEW = "PENDING_REVIEW",
  LIVE = "LIVE",
  REJECTED = "REJECTED",
  REMOVED = "REMOVED",
  SOLD_OUT = "SOLD_OUT"
}

export enum KnitterApplicationStatus {
  PENDING_REVIEW = "PENDING_REVIEW",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  SUSPENDED = "SUSPENDED"
}
